# Generated by Django 6.0.4 on 2026-05-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categoies'},
        ),
    ]
