# Generated by Django 6.0.4 on 2026-05-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_socaillink_alter_about_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocailLink',
            new_name='SocialLink',
        ),
    ]
